### ISSUE TITLE
Arithmetic expression fails to parse

### ISSUE THREAD

**Issue by LaurensRietveld** [RubenVerborgh/SPARQL.js#101]
This successfully parses:

```
SELECT * WHERE {
BIND (?a+1 AS ?b)
}
```

where this doesnt:

```
SELECT * WHERE {
BIND (?a-1 AS ?b)
}
```

That last part throws the following error:

```
     TypeError: $$[($0 - 1)].replace is not a function
      at Object.anonymous (/home/lrd900/triply/core/node_modules/sparqljs/lib/SparqlParser.js:429:45)
      at Parser.parse (/home/lrd900/triply/core/node_modules/sparqljs/lib/SparqlParser.js:660:36)
      at Parser.parser.parse [as parse] (/home/lrd900/triply/core/node_modules/sparqljs/sparql.js:25:37)
```

**Comment by LaurensRietveld** [comment]
It seems that SparqlJS regressed, and this is an issue again. Fine with keeping it closed, as this seems to already be reported in #118
