### ISSUE TITLE
Unable to create browser version

### ISSUE THREAD

**Issue by pheyvaer** [RubenVerborgh/SPARQL.js#16]
When following 
```
$ cd SPARQL.js
$ npm install
$ browserify sparql.js --standalone -u fs -u path -u _process sparqljs > sparqljs-browser.js
$ uglifyjs sparqljs-browser.js -c -m > sparqljs-browser-min.js
```
The third command gives the following error
```
Error: --standalone requires an export name argument
    at error (/usr/lib/node_modules/browserify/bin/args.js:116:17)
    at module.exports (/usr/lib/node_modules/browserify/bin/args.js:248:9)
    at Object.<anonymous> (/usr/lib/node_modules/browserify/bin/cmd.js:6:26)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by RubenVerborgh** [comment]
Thanks for reporting. Upgraded the browserify instructions to

```
browserify sparql.js -s sparqljs -i fs -i path -i _process  > sparqljs-browser.js
 ```
