### ISSUE TITLE
W3C test: DESCRIBE <u> fails with "cannot resolve relative IRI u because no base IRI was set"

### ISSUE THREAD

**Issue by grenik** [RubenVerborgh/SPARQL.js#163]
There is a positive syntax test among W3C SPARQL tests:
https://github.com/w3c/rdf-tests/blob/634dadcedba0177eb47975d642ae66949774834a/sparql11/data-r2/syntax-sparql2/syntax-form-describe01.rq

```sparql
DESCRIBE <u>
```
&nbsp;
It fails with the following error:
```
Error when parsing SPARQL query, will try to guess its type Error: Cannot resolve relative IRI u because no base IRI was set.
        at resolveIRI (//node_modules/sparqljs/lib/SparqlParser.js:878:13)
        at Object.anonymous (//node_modules/sparqljs/lib/SparqlParser.js:634:35)
        at Parser.parse (//node_modules/sparqljs/lib/SparqlParser.js:787:36)
        at Parser.parser.parse [as parse] (//node_modules/sparqljs/sparql.js:36:37)
        at parse (//tests/jest-runner/runall.spec.js:143:29)
```

**Comment by RubenVerborgh** [comment]
That makes sense to me; surely the W3C SPARQL tests have some base IRI Set.
