### ISSUE TITLE
"Library" example does not work

### ISSUE THREAD

**Issue by ktk** [RubenVerborgh/SPARQL.js#180]
It looks like the "Library" example in the README does not work, at least not in recent node:

```
 node sparql-normalize.js
/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:415
  return typeof object.termType === 'string';
                       ^

TypeError: Cannot read properties of undefined (reading 'termType')
    at isTerm (/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:415:24)
    at Generator.toExpression (/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:214:7)
    at Generator.<anonymous> (/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:40:25)
    at Array.map (<anonymous>)
    at mapJoin (/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:440:16)
    at Generator.toQuery (/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:38:14)
    at Object.stringify (/some-location/queries/node_modules/sparqljs/lib/SparqlGenerator.js:455:44)
    at Object.<anonymous> (/some-location/queries/sparql-normalize.js:11:32)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)

Node.js v22.6.0
```

Any ideas?

**Comment by ktk** [comment]
So I noticed it's this line which causes the problem:

```
parsedQuery.variables = ['?mickey'];
```

If I comment this, it works. The difference in the two generated JSON structures is:

without that line:

```json
{
  "queryType": "SELECT",
  "variables": [
    {
      "termType": "Variable",
      "value": "mickey"
    }
  ],
```

with that line:

```json
{
  "queryType": "SELECT",
  "variables": [
    "?mickey"
  ],
  "where": [
```

I also managed to provoke that in other queries:

query:

```sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?sub ?pred ?obj .
}
LIMIT 10
```

json that does not serialize anymore:

```json
{
  "queryType": "SELECT",
  "variables": [
    {}
  ],
  "where": [
    {
      "type": "bgp",
      "triples": [
        {
          "subject": {
            "termType": "Variable",
            "value": "sub"
          },
          "predicate": {
            "termType": "Variable",
            "value": "pred"
          },
          "object": {
            "termType": "Variable",
            "value": "obj"
          }
        }
      ]
    }
  ],
  "type": "query",
  "prefixes": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#"
  }
}
```

**Comment by RubenVerborgh** [comment]
Thanks @ktk, looks like `variables` is expecting RDF/JS terms. The README likely predates RDF/JS; I'll make sure string variables work again.
