### ISSUE TITLE
Update SPARQL.js to use the RDF/JS representation

### ISSUE THREAD

**Issue by white-gecko** [RubenVerborgh/SPARQL.js#61]
I try to create an `INSERT DATA` query based on an array of triples.
Motivated by the README text:

> The representation of triples is the same as that of the N3.js library.

I came up with the following code, where I just put the `triplesArray` in at the `triples` key:

    import {Generator} from 'sparqljs'
    import { DataFactory } from 'n3'
    const { namedNode, triple } = DataFactory

    var tripleArray = [triple(
      namedNode('http://example.org/some'),
      namedNode('http://www.w3.org/1999/02/22-rdf-syntax-ns#type'),
      namedNode('http://example.org/Something')
    )]
    var generator = new Generator()
    var updateStructure = {
      'type': 'update',
      'updates': [
        {
          'updateType': 'insert',
          'insert': [
            {
              'type': 'bgp',
              'triples': tripleArray
            }
          ]
        }
      ]
    }
    var updateString = generator.stringify(updateStructure)

but I end upp receiving the following error:

    node_modules/sparqljs/lib/SparqlGenerator.js:278
        var items = value.items.map(this.toEntity, this), path = value.pathType;
                                ^

    TypeError: Cannot read property 'map' of undefined
        at Generator.toEntity (node_modules/sparqljs/lib/SparqlGenerator.js:278:29)
        at Generator.encodeTriples (node_modules/sparqljs/lib/SparqlGenerator.js:122:23)
        at Generator.bgp (node_modules/sparqljs/lib/SparqlGenerator.js:105:15)
        at Generator.toPattern (node_modules/sparqljs/lib/SparqlGenerator.js:93:20)
        at Array.map (<anonymous>)
        at mapJoin (node_modules/sparqljs/lib/SparqlGenerator.js:351:16)
        at Generator.array (node_modules/sparqljs/lib/SparqlGenerator.js:101:10)
        at Generator.toPattern (node_modules/sparqljs/lib/SparqlGenerator.js:93:20)
        at Generator.group (node_modules/sparqljs/lib/SparqlGenerator.js:146:34)
        at Generator.toUpdate (node_modules/sparqljs/lib/SparqlGenerator.js:318:35)

How can I convert my triples to the correct format, which is accepted by sparql.js?

**Comment by RubenVerborgh** [comment]
> The representation of triples is the same as that of the N3.js library.

Woops, old documentation :-) N3 1.x has switched to the RDF/JS representation. The old N3 docs can help you for SPARQL.js: https://github.com/rdfjs/N3.js/tree/v0.11.3#triple-representation

(But at some point, we need to update SPARQL.js.)

**Comment by RubenVerborgh** [comment]
@white-gecko Yeah, I think @rubensworks has a package for that.

**Comment by rubensworks** [comment]
Indeed, the function [`quadToStringQuad `](https://www.npmjs.com/package/rdf-string#quad-to-string-based-quad) should do the trick until SPARQL.js has been updated to RDFJS.

**Comment by white-gecko** [comment]
Cool, that does the trick
